### ISSUE TITLE
Seminar

### ISSUE THREAD

**Issue by caophat17** [nphkhiem/2017-14BIT-TheBest-Case-Study-Project#1]

**Comment by caophat17** [comment]
[TOOL-Name.docx](https://github.com/nphkhiem/2017-14BIT-TheBest-Case-Study-Project/files/1050177/TOOL-Name.docx)
Cao Đường Phát- seminar

**Comment by luu-thanh-tu** [comment]
[DANH SÁCH CÁC BUGTRACKER.docx](https://github.com/nphkhiem/2017-14BIT-TheBest-Case-Study-Project/files/1056673/DANH.SACH.CAC.BUGTRACKER.docx)

**Comment by tuanlle63** [comment]
[qtest.docx](https://github.com/nphkhiem/2017-14BIT-TheBest-Case-Study-Project/files/1100224/qtest.docx)
